default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres141302-imobiliariabuenosaires.jelasticlw.com.br
  username: webadmin
  password: YTHdsf13881
 
  pool: 5

development:
  <<: *default
  database: imobi_development


test:
  <<: *default
  database: imobi_test


production:
  <<: *default
  database: imobi_production
