# Cidades
Cidade.create(:nome => 'Santa Rosa', :estado => 'RS')
#Bairros
Bairro.create(:cidade_id => 1, :nome => 'Aliança')
Bairro.create(:cidade_id => 1, :nome => 'Alto da Glória')
Bairro.create(:cidade_id => 1, :nome => 'Alto do Parque')
Bairro.create(:cidade_id => 1, :nome => 'Alto Glória')
Bairro.create(:cidade_id => 1, :nome => 'Alto Petrópolis')
Bairro.create(:cidade_id => 1, :nome => 'Alto Prenda')
Bairro.create(:cidade_id => 1, :nome => 'Alto S Timbaúva')
Bairro.create(:cidade_id => 1, :nome => 'Area Industrial')
Bairro.create(:cidade_id => 1, :nome => 'Ator da Timbaúva')
Bairro.create(:cidade_id => 1, :nome => 'Ator do Parque')
Bairro.create(:cidade_id => 1, :nome => 'Auxiliadora')
Bairro.create(:cidade_id => 1, :nome => 'Beatriz')
Bairro.create(:cidade_id => 1, :nome => 'Beco Marostega')
Bairro.create(:cidade_id => 1, :nome => 'Bela Vista')
Bairro.create(:cidade_id => 1, :nome => 'Bom Sucesso')
Bairro.create(:cidade_id => 1, :nome => 'Central')
Bairro.create(:cidade_id => 1, :nome => 'Centro')
Bairro.create(:cidade_id => 1, :nome => 'Cruzeiro')
Bairro.create(:cidade_id => 1, :nome => 'Distrito Industrial')
Bairro.create(:cidade_id => 1, :nome => 'Esplanada')
Bairro.create(:cidade_id => 1, :nome => 'Esquina Guia Lopes')
Bairro.create(:cidade_id => 1, :nome => 'Guarani')
Bairro.create(:cidade_id => 1, :nome => 'Ibanes')
Bairro.create(:cidade_id => 1, :nome => 'Identificar')
Bairro.create(:cidade_id => 1, :nome => 'Industrial')
Bairro.create(:cidade_id => 1, :nome => 'Interior')
Bairro.create(:cidade_id => 1, :nome => 'Jardim Petrópolis')
Bairro.create(:cidade_id => 1, :nome => 'Júlio Oliveira')
Bairro.create(:cidade_id => 1, :nome => 'Lajeado Ipe')
Bairro.create(:cidade_id => 1, :nome => 'Loteamento Bela Vista')
Bairro.create(:cidade_id => 1, :nome => 'Loteamento O Verdeesperanc')
Bairro.create(:cidade_id => 1, :nome => 'Loteamento Ouro Verde')
Bairro.create(:cidade_id => 1, :nome => 'Loteamento Terra')
Bairro.create(:cidade_id => 1, :nome => 'Ouro Verde')
Bairro.create(:cidade_id => 1, :nome => 'Parque Exposições')
Bairro.create(:cidade_id => 1, :nome => 'Peerimetro Urbano')
Bairro.create(:cidade_id => 1, :nome => 'Perimetro Urbano')
Bairro.create(:cidade_id => 1, :nome => 'Planalto')
Bairro.create(:cidade_id => 1, :nome => 'Polivalente')
Bairro.create(:cidade_id => 1, :nome => 'Recanto Timbaúva')
Bairro.create(:cidade_id => 1, :nome => 'Rodovia Rs')
Bairro.create(:cidade_id => 1, :nome => 'Saída Psto Cristo')
Bairro.create(:cidade_id => 1, :nome => 'Santa Ines')
Bairro.create(:cidade_id => 1, :nome => 'São Francisco')
Bairro.create(:cidade_id => 1, :nome => 'Sede')
Bairro.create(:cidade_id => 1, :nome => 'Subúrbios')
Bairro.create(:cidade_id => 1, :nome => 'Sulina')
Bairro.create(:cidade_id => 1, :nome => 'Timbaúva')
Bairro.create(:cidade_id => 1, :nome => 'Vicente Cardoso')
Bairro.create(:cidade_id => 1, :nome => 'Vila 7 de Setembro')
Bairro.create(:cidade_id => 1, :nome => 'Vila Agrícola')
Bairro.create(:cidade_id => 1, :nome => 'Vila Aliança')
Bairro.create(:cidade_id => 1, :nome => 'Vila Balneária')
Bairro.create(:cidade_id => 1, :nome => 'Vila Balneário')
Bairro.create(:cidade_id => 1, :nome => 'Vila Bancários')
Bairro.create(:cidade_id => 1, :nome => 'Vila Beatriz')
Bairro.create(:cidade_id => 1, :nome => 'Vila Coohab')
Bairro.create(:cidade_id => 1, :nome => 'Vila Coohabpro Morar')
Bairro.create(:cidade_id => 1, :nome => 'Vila dos Bancários')
Bairro.create(:cidade_id => 1, :nome => 'Vila Esmeralda')
Bairro.create(:cidade_id => 1, :nome => 'Vila Esperana')
Bairro.create(:cidade_id => 1, :nome => 'Vila Esperança')
Bairro.create(:cidade_id => 1, :nome => 'Vila Flores')
Bairro.create(:cidade_id => 1, :nome => 'Vila Glória')
Bairro.create(:cidade_id => 1, :nome => 'Vila Ibanez')
Bairro.create(:cidade_id => 1, :nome => 'Vila Jardim')
Bairro.create(:cidade_id => 1, :nome => 'Vila Kerber')
Bairro.create(:cidade_id => 1, :nome => 'Vila N')
Bairro.create(:cidade_id => 1, :nome => 'Vila Nova')
Bairro.create(:cidade_id => 1, :nome => 'Vila Oliveira')
Bairro.create(:cidade_id => 1, :nome => 'Vila Pereira')
Bairro.create(:cidade_id => 1, :nome => 'Vila Piekala')
Bairro.create(:cidade_id => 1, :nome => 'Vila Planalto')
Bairro.create(:cidade_id => 1, :nome => 'Vila Prenda')
Bairro.create(:cidade_id => 1, :nome => 'Vila Progresso')
Bairro.create(:cidade_id => 1, :nome => 'Vila Roma')
Bairro.create(:cidade_id => 1, :nome => 'Vila Santa Ines')
Bairro.create(:cidade_id => 1, :nome => 'Vila Santos')
Bairro.create(:cidade_id => 1, :nome => 'Vila São Francisco')
Bairro.create(:cidade_id => 1, :nome => 'Vila Sulina')
Bairro.create(:cidade_id => 1, :nome => 'Vila Timbaúva')
Bairro.create(:cidade_id => 1, :nome => 'Vila Winkelman')
Bairro.create(:cidade_id => 1, :nome => 'Vila Winkelmann')
Bairro.create(:cidade_id => 1, :nome => 'Zona Rural')
#Situação
Situacao.create(:nome => 'Disponível')
Situacao.create(:nome => 'Em análise')
Situacao.create(:nome => 'Vendido')
#Tipos
Tipo.create(:nome => 'Casa')
Tipo.create(:nome => 'Apartamento')
Tipo.create(:nome => 'Terreno')
#categorias
Categoria.create(:nome => 'Venda')
Categoria.create(:nome => 'Locação')
